import PDFDocument from "pdfkit";
import path from "path";
import QRCode from "qrcode";

// Set font path for PDFKit - use bundled fonts
const fontPath = path.join(process.cwd(), 'node_modules', 'pdfkit', 'js', 'data');

// Types for Merged Invoice PDF generation
type MergedInvoice = {
  id: number;
  invoiceNumber: string | null;
  saleDate: string;
  customerName: string | null;
  customerPhone: string | null;
  totalKwd: string | null;
  lineItems: Array<{
    itemName: string;
    quantity: number | null;
    priceKwd: string | null;
    totalKwd: string | null;
  }>;
  verificationCode?: string;
};

// Types for Bank Pack PDF generation
type BankPackInvoice = {
  invoiceNumber: string | null;
  saleDate: string;
  customerName: string | null;
  totalKwd: string | null;
  fxCurrency: string | null;
  fxRate: string | null;
  totalFx: string | null;
  lineItems: Array<{
    itemName: string;
    quantity: number | null;
    priceKwd: string | null;
    totalKwd: string | null;
  }>;
  verificationCode?: string;
};

type BankPackPayment = {
  voucherNumber: string | null;
  paymentDate: string;
  partyName: string | null;
  amount: string;
  direction: string;
  paymentMethod: string | null;
  accountName: string | null;
  reference: string | null;
  verificationCode?: string;
};

type BankPackData = {
  startDate: string;
  endDate: string;
  invoices: BankPackInvoice[];
  payments: BankPackPayment[];
  summary: {
    totalInvoices: number;
    totalInvoiceAmount: number;
    totalPaymentsIn: number;
    totalPaymentsInAmount: number;
    totalPaymentsOut: number;
    totalPaymentsOutAmount: number;
  };
};

const COMPANY_INFO = {
  name: "Iqbal Electronics Co. WLL",
  address: "Salmiya, Block 12, Salem Al-Mubarak Street",
  city: "Kuwait City, Kuwait",
  phone: "+965 XXXX XXXX",
  email: "info@iqbalelectronics.com",
  license: "CR: XXXXXX",
};

// Helper to format numbers
function formatAmount(value: string | number | null, decimals = 3): string {
  if (value === null || value === undefined) return "0.000";
  const num = typeof value === "string" ? parseFloat(value) : value;
  return num.toLocaleString("en-US", {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });
}

// Helper to format date
function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

// Generate Bank Pack PDF with A4 format
export async function generateBankPackPDF(data: BankPackData): Promise<Buffer> {
  return new Promise<Buffer>(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        size: "A4", 
        margin: 50,
        bufferPages: true,
        font: 'Helvetica',
      });
      const chunks: Buffer[] = [];
      
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const pageWidth = doc.page.width - 100; // 50 margin each side
      let pageNumber = 0;

      // Function to add header/footer to each page
      const addPageHeaderFooter = (pageNum: number, totalPages: number) => {
        const y = doc.page.height - 40;
        doc.fontSize(8).fillColor("#666");
        doc.text(`Page ${pageNum} of ${totalPages}`, 50, y, { align: "center", width: pageWidth });
        doc.text("Generated by Iqbal Electronics ERP System", 50, y + 10, { align: "center", width: pageWidth });
      };

      // ============== COVER PAGE ==============
      pageNumber++;
      
      // Company Header
      doc.fontSize(20).fillColor("#1a1a2e").text(COMPANY_INFO.name, { align: "center" });
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor("#555").text(COMPANY_INFO.address, { align: "center" });
      doc.text(COMPANY_INFO.city, { align: "center" });
      doc.moveDown(2);

      // Title
      doc.fontSize(18).fillColor("#1a1a2e").text("BANK COMPLIANCE REPORT", { align: "center" });
      doc.moveDown(0.5);
      doc.fontSize(12).fillColor("#333").text("Financial Vouchers Summary", { align: "center" });
      doc.moveDown(2);

      // Period Box
      doc.rect(150, doc.y, 295, 60).stroke("#1a1a2e");
      doc.fontSize(11).fillColor("#1a1a2e").text("REPORT PERIOD", 150, doc.y + 10, { width: 295, align: "center" });
      doc.fontSize(14).fillColor("#333").text(`${formatDate(data.startDate)} - ${formatDate(data.endDate)}`, 150, doc.y + 5, { width: 295, align: "center" });
      doc.moveDown(4);

      // Summary Statistics
      doc.fontSize(14).fillColor("#1a1a2e").text("Summary", 50);
      doc.moveDown(0.5);
      
      // Summary table
      const summaryY = doc.y;
      doc.fontSize(10).fillColor("#333");
      
      // Left column - Sales
      doc.text("SALES INVOICES", 50, summaryY, { underline: true });
      doc.text(`Total Count: ${data.summary.totalInvoices}`, 50, summaryY + 20);
      doc.text(`Total Amount: ${formatAmount(data.summary.totalInvoiceAmount)} KWD`, 50, summaryY + 35);
      
      // Right column - Payments
      doc.text("PAYMENTS RECEIVED (IN)", 300, summaryY, { underline: true });
      doc.text(`Total Count: ${data.summary.totalPaymentsIn}`, 300, summaryY + 20);
      doc.text(`Total Amount: ${formatAmount(data.summary.totalPaymentsInAmount)} KWD`, 300, summaryY + 35);
      
      doc.text("PAYMENTS MADE (OUT)", 300, summaryY + 60, { underline: true });
      doc.text(`Total Count: ${data.summary.totalPaymentsOut}`, 300, summaryY + 80);
      doc.text(`Total Amount: ${formatAmount(data.summary.totalPaymentsOutAmount)} KWD`, 300, summaryY + 95);
      
      doc.moveDown(8);
      
      // Net Cash Position
      const netCash = data.summary.totalPaymentsInAmount - data.summary.totalPaymentsOutAmount;
      doc.fontSize(12).fillColor("#1a1a2e").text("Net Cash Movement:", 50);
      doc.fontSize(14).fillColor(netCash >= 0 ? "#2e7d32" : "#c62828")
        .text(`${netCash >= 0 ? "+" : ""}${formatAmount(netCash)} KWD`, 200, doc.y - 14);
      
      doc.moveDown(4);
      
      // Prepared/Reviewed section
      doc.fontSize(10).fillColor("#333");
      doc.text("Prepared By: _______________________", 50, doc.page.height - 150);
      doc.text("Date: _______________________", 50, doc.page.height - 130);
      doc.text("Reviewed By: _______________________", 300, doc.page.height - 150);
      doc.text("Date: _______________________", 300, doc.page.height - 130);
      
      // Currency note
      doc.fontSize(8).fillColor("#666")
        .text("All amounts in Kuwaiti Dinars (KWD) unless otherwise stated.", 50, doc.page.height - 80, { align: "center", width: pageWidth });

      // ============== SALES INVOICES SECTION ==============
      if (data.invoices.length > 0) {
        doc.addPage();
        pageNumber++;
        
        doc.fontSize(16).fillColor("#1a1a2e").text("SECTION A: SALES INVOICES", { align: "center" });
        doc.moveDown();
        doc.fontSize(10).fillColor("#555").text(`Period: ${formatDate(data.startDate)} - ${formatDate(data.endDate)}`, { align: "center" });
        doc.moveDown(2);

        // Table Header
        const tableTop = doc.y;
        const colWidths = [70, 70, 150, 80, 80];
        const cols = [50, 120, 190, 340, 420];
        
        doc.fontSize(9).fillColor("#fff");
        doc.rect(50, tableTop, pageWidth, 20).fill("#1a1a2e");
        doc.text("Inv. No.", cols[0] + 5, tableTop + 5);
        doc.text("Date", cols[1] + 5, tableTop + 5);
        doc.text("Customer", cols[2] + 5, tableTop + 5);
        doc.text("Amount (KWD)", cols[3] + 5, tableTop + 5);
        doc.text("FX Amount", cols[4] + 5, tableTop + 5);
        
        let rowY = tableTop + 25;
        let subtotal = 0;
        
        for (let i = 0; i < data.invoices.length; i++) {
          const inv = data.invoices[i];
          const amount = parseFloat(inv.totalKwd || "0");
          subtotal += amount;
          
          // Check if we need a new page
          if (rowY > doc.page.height - 100) {
            doc.addPage();
            pageNumber++;
            rowY = 50;
            
            // Repeat header
            doc.fontSize(9).fillColor("#fff");
            doc.rect(50, rowY, pageWidth, 20).fill("#1a1a2e");
            doc.text("Inv. No.", cols[0] + 5, rowY + 5);
            doc.text("Date", cols[1] + 5, rowY + 5);
            doc.text("Customer", cols[2] + 5, rowY + 5);
            doc.text("Amount (KWD)", cols[3] + 5, rowY + 5);
            doc.text("FX Amount", cols[4] + 5, rowY + 5);
            rowY += 25;
          }
          
          // Alternate row background
          if (i % 2 === 0) {
            doc.rect(50, rowY - 3, pageWidth, 18).fill("#f5f5f5");
          }
          
          doc.fontSize(9).fillColor("#333");
          doc.text(inv.invoiceNumber || "-", cols[0] + 5, rowY, { width: colWidths[0] - 10 });
          doc.text(formatDate(inv.saleDate), cols[1] + 5, rowY);
          doc.text((inv.customerName || "Cash").substring(0, 25), cols[2] + 5, rowY, { width: colWidths[2] - 10 });
          doc.text(formatAmount(inv.totalKwd), cols[3] + 5, rowY);
          
          if (inv.fxCurrency && inv.totalFx) {
            doc.text(`${formatAmount(inv.totalFx, 2)} ${inv.fxCurrency}`, cols[4] + 5, rowY);
          } else {
            doc.text("-", cols[4] + 5, rowY);
          }
          
          rowY += 18;
        }
        
        // Subtotal row
        doc.rect(50, rowY, pageWidth, 20).fill("#e0e0e0");
        doc.fontSize(10).fillColor("#1a1a2e");
        doc.text("TOTAL:", cols[2] + 5, rowY + 5);
        doc.text(formatAmount(subtotal), cols[3] + 5, rowY + 5);
      }

      // ============== PAYMENTS SECTION ==============
      if (data.payments.length > 0) {
        doc.addPage();
        pageNumber++;
        
        doc.fontSize(16).fillColor("#1a1a2e").text("SECTION B: PAYMENT VOUCHERS", { align: "center" });
        doc.moveDown();
        doc.fontSize(10).fillColor("#555").text(`Period: ${formatDate(data.startDate)} - ${formatDate(data.endDate)}`, { align: "center" });
        doc.moveDown(2);

        // Table Header
        const tableTop = doc.y;
        const cols = [50, 100, 150, 280, 350, 420];
        
        doc.fontSize(9).fillColor("#fff");
        doc.rect(50, tableTop, pageWidth, 20).fill("#1a1a2e");
        doc.text("Voucher", cols[0] + 5, tableTop + 5);
        doc.text("Date", cols[1] + 5, tableTop + 5);
        doc.text("Party", cols[2] + 5, tableTop + 5);
        doc.text("Type", cols[3] + 5, tableTop + 5);
        doc.text("Method", cols[4] + 5, tableTop + 5);
        doc.text("Amount", cols[5] + 5, tableTop + 5);
        
        let rowY = tableTop + 25;
        let subtotalIn = 0;
        let subtotalOut = 0;
        
        for (let i = 0; i < data.payments.length; i++) {
          const pmt = data.payments[i];
          const amount = parseFloat(pmt.amount || "0");
          if (pmt.direction === "in") {
            subtotalIn += amount;
          } else {
            subtotalOut += amount;
          }
          
          // Check if we need a new page
          if (rowY > doc.page.height - 100) {
            doc.addPage();
            pageNumber++;
            rowY = 50;
            
            // Repeat header
            doc.fontSize(9).fillColor("#fff");
            doc.rect(50, rowY, pageWidth, 20).fill("#1a1a2e");
            doc.text("Voucher", cols[0] + 5, rowY + 5);
            doc.text("Date", cols[1] + 5, rowY + 5);
            doc.text("Party", cols[2] + 5, rowY + 5);
            doc.text("Type", cols[3] + 5, rowY + 5);
            doc.text("Method", cols[4] + 5, rowY + 5);
            doc.text("Amount", cols[5] + 5, rowY + 5);
            rowY += 25;
          }
          
          // Alternate row background
          if (i % 2 === 0) {
            doc.rect(50, rowY - 3, pageWidth, 18).fill("#f5f5f5");
          }
          
          doc.fontSize(9).fillColor("#333");
          doc.text(pmt.voucherNumber || "-", cols[0] + 5, rowY);
          doc.text(formatDate(pmt.paymentDate), cols[1] + 5, rowY);
          doc.text((pmt.partyName || "-").substring(0, 20), cols[2] + 5, rowY);
          doc.fillColor(pmt.direction === "in" ? "#2e7d32" : "#c62828")
            .text(pmt.direction === "in" ? "RECEIVED" : "PAID", cols[3] + 5, rowY);
          doc.fillColor("#333").text(pmt.paymentMethod || "-", cols[4] + 5, rowY);
          doc.text(formatAmount(pmt.amount), cols[5] + 5, rowY);
          
          rowY += 18;
        }
        
        // Subtotal rows
        doc.rect(50, rowY, pageWidth, 20).fill("#c8e6c9");
        doc.fontSize(10).fillColor("#2e7d32");
        doc.text("TOTAL RECEIVED (IN):", cols[2] + 5, rowY + 5);
        doc.text(formatAmount(subtotalIn), cols[5] + 5, rowY + 5);
        rowY += 22;
        
        doc.rect(50, rowY, pageWidth, 20).fill("#ffcdd2");
        doc.fillColor("#c62828");
        doc.text("TOTAL PAID (OUT):", cols[2] + 5, rowY + 5);
        doc.text(formatAmount(subtotalOut), cols[5] + 5, rowY + 5);
        rowY += 22;
        
        const netPayments = subtotalIn - subtotalOut;
        doc.rect(50, rowY, pageWidth, 20).fill("#e0e0e0");
        doc.fillColor(netPayments >= 0 ? "#2e7d32" : "#c62828");
        doc.text("NET CASH FLOW:", cols[2] + 5, rowY + 5);
        doc.text(`${netPayments >= 0 ? "+" : ""}${formatAmount(netPayments)}`, cols[5] + 5, rowY + 5);
      }

      // Add page numbers to all pages
      const totalPages = doc.bufferedPageRange().count;
      for (let i = 0; i < totalPages; i++) {
        doc.switchToPage(i);
        addPageHeaderFooter(i + 1, totalPages);
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

export function generateRecommendationsPDF(): Buffer {
  return new Promise<Buffer>((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];
      
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      doc.fontSize(24).fillColor("#1a1a2e").text("ERP Modernization Recommendations", { align: "center" });
      doc.moveDown();
      doc.fontSize(12).fillColor("#666").text("Iqbal Electronics Co. WLL", { align: "center" });
      doc.text(new Date().toLocaleDateString(), { align: "center" });
      doc.moveDown(2);

      doc.fontSize(16).fillColor("#1a1a2e").text("High Impact Features (Recommend Now)");
      doc.moveDown(0.5);

      doc.fontSize(12).fillColor("#333").text("1. AI-Powered Insights", { underline: true });
      doc.fontSize(10).fillColor("#555");
      doc.text("  - Smart Dashboard: AI-generated daily summary of business performance");
      doc.text("  - Demand Forecasting: Predict which phones will sell next month");
      doc.text("  - Auto-suggestions: Reorder alerts for low stock items");
      doc.moveDown();

      doc.fontSize(12).fillColor("#333").text("2. Conversational Interface (AI Chat)", { underline: true });
      doc.fontSize(10).fillColor("#555");
      doc.text('  - Ask questions like: "What were total sales last week?"');
      doc.text("  - No need to navigate menus - just type naturally");
      doc.moveDown();

      doc.fontSize(12).fillColor("#333").text("3. Mobile App", { underline: true });
      doc.fontSize(10).fillColor("#555");
      doc.text("  - Sales reps can create invoices on the go");
      doc.text("  - Real-time stock check from phone");
      doc.text("  - Push notifications for low stock, payment reminders");
      doc.moveDown();

      doc.fontSize(12).fillColor("#333").text("4. WhatsApp Integration", { underline: true });
      doc.fontSize(10).fillColor("#555");
      doc.text("  - Send invoices directly to customers");
      doc.text("  - Payment reminders");
      doc.text("  - Delivery confirmations");
      doc.moveDown(2);

      doc.fontSize(16).fillColor("#1a1a2e").text("Medium Priority (Next Phase)");
      doc.moveDown(0.5);

      doc.fontSize(12).fillColor("#333").text("5. Advanced Analytics Dashboard", { underline: true });
      doc.fontSize(10).fillColor("#555");
      doc.text("  - Visual charts: Sales trends, profit margins, top products");
      doc.text("  - Compare branches side-by-side");
      doc.text("  - Export reports to PDF/Excel");
      doc.moveDown();

      doc.fontSize(12).fillColor("#333").text("6. Customer Portal", { underline: true });
      doc.fontSize(10).fillColor("#555");
      doc.text("  - Customers view their purchase history");
      doc.text("  - Download their own invoices");
      doc.text("  - Check their balance/credit");
      doc.moveDown();

      doc.fontSize(12).fillColor("#333").text("7. Supplier Price Comparison", { underline: true });
      doc.fontSize(10).fillColor("#555");
      doc.text("  - Track prices from different suppliers");
      doc.text("  - Alert when a supplier offers better price");
      doc.text("  - Historical price trends");
      doc.moveDown(2);

      doc.fontSize(16).fillColor("#1a1a2e").text("Future Enhancements");
      doc.moveDown(0.5);

      doc.fontSize(12).fillColor("#333").text("8. Barcode/QR Scanning", { underline: true });
      doc.fontSize(10).fillColor("#555");
      doc.text("  - Scan IMEI to instantly add to sale");
      doc.text("  - Print barcode labels for inventory");
      doc.moveDown();

      doc.fontSize(12).fillColor("#333").text("9. Multi-Currency Auto-Rates", { underline: true });
      doc.fontSize(10).fillColor("#555");
      doc.text("  - Fetch live exchange rates automatically");
      doc.text("  - Auto-convert USD/AED to KWD");
      doc.moveDown();

      doc.fontSize(12).fillColor("#333").text("10. ESG/Sustainability Tracking", { underline: true });
      doc.fontSize(10).fillColor("#555");
      doc.text("  - Track device recycling/returns");
      doc.text("  - Environmental compliance reports");
      doc.moveDown(2);

      doc.fontSize(16).fillColor("#1a1a2e").text("Priority Matrix");
      doc.moveDown(0.5);
      
      doc.fontSize(10).fillColor("#555");
      doc.text("Priority 1: AI Dashboard Summary - Medium Effort, High Impact");
      doc.text("Priority 2: Mobile-Responsive Design - Low Effort, High Impact");
      doc.text("Priority 3: WhatsApp Integration - Medium Effort, High Impact");
      doc.text("Priority 4: Customer Portal - Medium Effort, Medium Impact");
      doc.moveDown(2);

      doc.fontSize(8).fillColor("#999").text("Generated by Iqbal Electronics ERP System", { align: "center" });

      doc.end();
    } catch (error) {
      reject(error);
    }
  }) as unknown as Buffer;
}

// Generate Merged Invoices PDF (A5 format, multiple invoices in one PDF)
// Matches the HTML template from SalesOrderDetail.tsx
export async function generateMergedInvoicesPDF(invoices: MergedInvoice[], date: string): Promise<Buffer> {
  return new Promise<Buffer>(async (resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        size: "A5", 
        margin: 20,
        bufferPages: true,
        font: 'Helvetica',
      });
      const chunks: Buffer[] = [];
      
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const margin = 20;
      const pageWidth = doc.page.width - (margin * 2);

      for (let i = 0; i < invoices.length; i++) {
        const invoice = invoices[i];
        
        if (i > 0) {
          doc.addPage();
        }

        // Generate QR code for verification
        let qrDataUrl: string | null = null;
        if (invoice.verificationCode) {
          try {
            qrDataUrl = await QRCode.toDataURL(
              `https://${process.env.REPL_SLUG || 'app'}.replit.app/verify?code=${invoice.verificationCode}`,
              { width: 60, margin: 1 }
            );
          } catch (e) {
            // Skip QR if generation fails
          }
        }

        // Top Title - "Credit Invoice" centered and underlined
        doc.fontSize(11).font('Helvetica-Bold').fillColor("#000").text("Credit Invoice", margin, margin, { 
          align: "center", 
          width: pageWidth,
          underline: true 
        });
        doc.moveDown(0.3);

        // Header Row - Logo section (left) and Company section (right)
        const headerY = doc.y;
        
        // Left - Company Logo image
        const logoPath = path.join(process.cwd(), 'attached_assets', 'erpLogo_2_1765470830494.png');
        try {
          doc.image(logoPath, margin, headerY, { height: 30 });
        } catch (e) {
          // Fallback to text if image fails
          doc.fontSize(20).font('Helvetica-Bold').fillColor("#1a1a2e").text("IEC", margin, headerY);
        }
        doc.fontSize(6).font('Helvetica').fillColor("#333").text("شركة إقبال للأجهزة إلكترونية ذ.م.م", margin, headerY + 32);
        
        // Right - Company info
        doc.fontSize(10).font('Helvetica-Bold').fillColor("#1a1a2e").text("Iqbal Electronics Co. WLL", margin, headerY, { 
          width: pageWidth, 
          align: "right" 
        });
        doc.fontSize(7).font('Helvetica').fillColor("#333").text("Phone no.: +965 55584488", margin, headerY + 12, { 
          width: pageWidth, 
          align: "right" 
        });
        
        doc.y = headerY + 35;

        // Second Title
        doc.fontSize(9).font('Helvetica-Bold').fillColor("#000").text("Credit Invoice", margin, doc.y, { 
          align: "center", 
          width: pageWidth 
        });
        doc.moveDown(0.3);

        // Info Row - Bill To (left) and Invoice Details (right)
        const infoY = doc.y;
        
        // Bill To section
        doc.fontSize(8).font('Helvetica-Bold').text("Bill To", margin, infoY);
        doc.fontSize(7).font('Helvetica-Bold').text(invoice.customerName || "Walk-in Customer", margin, infoY + 10);
        doc.font('Helvetica').text("Kuwait", margin, infoY + 19);
        doc.text(`Contact No. : ${invoice.customerPhone || "—"}`, margin, infoY + 28);

        // Invoice Details section
        doc.fontSize(8).font('Helvetica-Bold').text("Invoice Details", margin, infoY, { width: pageWidth, align: "right" });
        doc.fontSize(7).font('Helvetica').text(`Invoice No. : ${invoice.invoiceNumber || invoice.id}`, margin, infoY + 10, { width: pageWidth, align: "right" });
        doc.text(`Date : ${formatDate(invoice.saleDate)}`, margin, infoY + 19, { width: pageWidth, align: "right" });

        doc.y = infoY + 42;

        // Items Table - matching HTML template columns: #, Item name, Item Code, Quantity, Price/Unit, VAT%, Final Rate, Amount
        const tableTop = doc.y;
        const colWidths = [18, 95, 55, 32, 45, 28, 45, 50];
        const tableWidth = colWidths.reduce((a, b) => a + b, 0);
        const headers = ["#", "Item name", "Item Code", "Qty", "Price/Unit", "VAT%", "Final Rate", "Amount"];
        const rowHeight = 12;

        // Table header
        doc.fillColor("#000");
        let x = margin;
        headers.forEach((header, idx) => {
          doc.rect(x, tableTop, colWidths[idx], rowHeight).stroke();
          const align = idx === 0 || idx === 3 || idx === 5 ? "center" : (idx >= 4 ? "right" : "left");
          doc.fontSize(6).font('Helvetica-Bold').text(header, x + 2, tableTop + 3, { 
            width: colWidths[idx] - 4, 
            align: align as any
          });
          x += colWidths[idx];
        });

        // Table rows
        let rowY = tableTop + rowHeight;
        let totalQuantity = 0;
        const subtotal = parseFloat(invoice.totalKwd || "0");

        invoice.lineItems.forEach((item, idx) => {
          const qty = item.quantity || 0;
          totalQuantity += qty;
          const price = parseFloat(item.priceKwd || "0");
          const amount = parseFloat(item.totalKwd || "0");
          const itemName = item.itemName || "Item";

          x = margin;
          
          const rowData = [
            { text: `${idx + 1}`, align: "center" },
            { text: itemName.substring(0, 25), align: "left" },
            { text: "—", align: "left" },
            { text: `${qty}`, align: "center" },
            { text: `KWD ${price.toFixed(1)}`, align: "right" },
            { text: "0%", align: "center" },
            { text: `KWD ${price.toFixed(1)}`, align: "right" },
            { text: `KWD ${amount.toFixed(1)}`, align: "right" }
          ];

          rowData.forEach((data, colIdx) => {
            doc.rect(x, rowY, colWidths[colIdx], rowHeight).stroke();
            doc.fontSize(7).font('Helvetica').text(data.text, x + 2, rowY + 3, { 
              width: colWidths[colIdx] - 4, 
              align: data.align as any 
            });
            x += colWidths[colIdx];
          });

          rowY += rowHeight;
        });

        // Total row
        x = margin;
        const totalRowData = [
          { text: "", align: "left" },
          { text: "Total", align: "left", bold: true },
          { text: "", align: "left" },
          { text: `${totalQuantity}`, align: "center", bold: true },
          { text: "", align: "right" },
          { text: "", align: "center" },
          { text: "", align: "right" },
          { text: `KWD ${subtotal.toFixed(1)}`, align: "right", bold: true }
        ];

        totalRowData.forEach((data, colIdx) => {
          doc.rect(x, rowY, colWidths[colIdx], rowHeight).stroke();
          if (data.text) {
            doc.fontSize(7).font(data.bold ? 'Helvetica-Bold' : 'Helvetica').text(data.text, x + 2, rowY + 3, { 
              width: colWidths[colIdx] - 4, 
              align: data.align as any 
            });
          }
          x += colWidths[colIdx];
        });
        rowY += rowHeight + 5;

        // Bottom Section - two columns
        const bottomY = rowY;
        const leftColWidth = 180;
        const rightColX = margin + leftColWidth + 10;
        const rightColWidth = pageWidth - leftColWidth - 10;
        
        // Left column - Amount in words box
        doc.fontSize(6).font('Helvetica-Bold').fillColor("#000");
        doc.rect(margin, bottomY, leftColWidth, 12).stroke();
        doc.text("Invoice Amount in Words", margin + 3, bottomY + 3);
        
        doc.rect(margin, bottomY + 12, leftColWidth, 16).stroke();
        doc.fontSize(7).font('Helvetica').text(numberToWords(subtotal), margin + 3, bottomY + 16, { width: leftColWidth - 6 });
        
        // Payment mode box
        doc.fontSize(6).font('Helvetica-Bold');
        doc.rect(margin, bottomY + 32, leftColWidth, 10).stroke();
        doc.text("Payment mode", margin + 3, bottomY + 35);
        
        doc.rect(margin, bottomY + 42, leftColWidth, 14).stroke();
        doc.fontSize(7).font('Helvetica').text("Credit", margin + 3, bottomY + 47);

        // Right column - Amounts table
        doc.fontSize(6).font('Helvetica-Bold');
        doc.rect(rightColX, bottomY, rightColWidth, 10).stroke();
        doc.text("Amounts", rightColX + 3, bottomY + 3);
        
        const amountRows = [
          { label: "Sub Total", value: `KWD ${subtotal.toFixed(1)}` },
          { label: "Total", value: `KWD ${subtotal.toFixed(1)}` },
          { label: "Balance", value: `KWD ${subtotal.toFixed(1)}` }
        ];
        
        let amountY = bottomY + 10;
        amountRows.forEach(row => {
          doc.rect(rightColX, amountY, rightColWidth, 12).stroke();
          doc.fontSize(7).font('Helvetica-Bold').text(row.label, rightColX + 3, amountY + 3, { width: rightColWidth / 2 - 6 });
          doc.font('Helvetica').text(row.value, rightColX + rightColWidth / 2, amountY + 3, { width: rightColWidth / 2 - 3, align: "right" });
          amountY += 12;
        });

        // Footer with QR code
        const footerY = doc.page.height - 50;
        doc.moveTo(margin, footerY).lineTo(margin + pageWidth, footerY).stroke();
        
        doc.fontSize(6).fillColor("#666").text("This is a computer generated document.", margin, footerY + 5);
        doc.text("No signature required. Validate by scanning QR code.", margin, footerY + 12);

        if (qrDataUrl) {
          try {
            doc.image(qrDataUrl, pageWidth - 10, footerY + 2, { width: 40, height: 40 });
            doc.fontSize(5).text("Scan to verify", pageWidth - 10, footerY + 43, { width: 40, align: "center" });
          } catch (e) {
            // Skip if QR image fails
          }
        }
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

// Helper to convert number to words
function numberToWords(num: number): string {
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];
  const teens = ['Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];

  if (num === 0) return 'Zero Dinars Only';
  
  const intPart = Math.floor(num);
  const decPart = Math.round((num - intPart) * 1000);
  
  const convertHundreds = (n: number): string => {
    if (n === 0) return '';
    if (n < 10) return ones[n];
    if (n < 20) return teens[n - 10];
    if (n < 100) return tens[Math.floor(n / 10)] + (n % 10 ? ' ' + ones[n % 10] : '');
    return ones[Math.floor(n / 100)] + ' Hundred' + (n % 100 ? ' ' + convertHundreds(n % 100) : '');
  };
  
  let result = '';
  if (intPart >= 1000) {
    result += convertHundreds(Math.floor(intPart / 1000)) + ' Thousand ';
  }
  result += convertHundreds(intPart % 1000);
  
  if (decPart > 0) {
    result += ' and ' + convertHundreds(decPart) + ' Fils';
  } else {
    result += ' Dinars Only';
  }
  
  return result.trim();
}
